name: StaffMode
version: 1.0
main: com.ckanto.staffmode.StaffModePlugin
author: ckanto
description: Modalita staff con strumenti rapidi in hotbar.
commands:
  staff:
    description: Apri la modalita staff
    usage: /staff [off]
    permission: staffmode.use
  leavestaff:
    description: Esci dalla modalita staff
    usage: /leavestaff
    permission: staffmode.use
permissions:
  staffmode.use:
    description: Permette di usare la modalita staff
    default: op
